name: Compile Shiny app to static site under docs/
on:
  # push
  workflow_dispatch:
  
jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install shinylive
      run: pip install shinylive

    - name: Clear existing compiled app
      run: rm -rf docs
      
    - name: Build static version of shiny app
      run: shinylive export src_shiny_app docs

    - name: Commit changes
      run: |
          git config --global user.name 'nickynicolson'
          git config --global user.email 'n.nicolson@kew.org'
          git add docs/*
          git commit -am "shinylive compilation"
          git push    


  # Build job
  build:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload docs subdir
          path: 'docs'

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
